[[analyzers]]
name = "nginx"
groupingKeys = ["Method", "Url", "Protocol"]
sortKeys = ["Total"]
limit = 100
diffs = ["Count", "Total", "Mean"]

[analyzers.parser]
regexp = '''^(\S+) - (\S+) \[([^\]]+)\] "(?P<Method>\S+) (?P<Url>\S+) (?P<Protocol>[^"]+)" (?P<Status>\d+) (?P<Bytes>\d+) "([^"]+)" "(?P<UserAgent>[^"]+)" (?P<ResponseTime>\S+)$'''

[[analyzers.parser.columns]]
name = "Method"

[[analyzers.parser.columns]]
name = "Url"
specifier.name = "Url"
converters = [
  { type = "queryParams", options = { replacer = "*" } },
  { type = "regexp", options = { replacer = "(ulid)", pattern = '''[0-9a-zA-Z]{26}''' } },
  { type = "regexp", options = { replacer = "(uuid)", pattern = '''[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}''' } },
  { type = "regexp", options = { replacer = "/assets/*", pattern = '''/assets/.*''' } },
  { type = "regexp", options = { replacer = "/images/*", pattern = '''/images/.*''' } },
]

[[analyzers.parser.columns]]
name = "Protocol"

[[analyzers.parser.columns]]
name = "Status"
converters = [{ type = "parseInt" }]

[[analyzers.parser.columns]]
name = "Bytes"
converters = [{ type = "parseInt" }]

[[analyzers.parser.columns]]
name = "UserAgent"

[[analyzers.parser.columns]]
name = "ResponseTime"
converters = [{ type = "parseFloat64" }]


[[analyzers.query]]
name = "Count"
from = "Url"
function = "count"

[[analyzers.query]]
name = "Total"
from = "ResponseTime"
function = "sum"

[[analyzers.query]]
name = "Mean"
from = "ResponseTime"
function = "mean"

[[analyzers.query]]
name = "Stddev"
from = "ResponseTime"
function = "stddev"

[[analyzers.query]]
name = "Min"
from = "ResponseTime"
function = "min"

[[analyzers.query]]
name = "P50"
from = "ResponseTime"
function = "p50"

[[analyzers.query]]
name = "P90"
from = "ResponseTime"
function = "p90"

[[analyzers.query]]
name = "P95"
from = "ResponseTime"
function = "p95"

[[analyzers.query]]
name = "P99"
from = "ResponseTime"
function = "p99"

[[analyzers.query]]
name = "Max"
from = "ResponseTime"
function = "max"

[[analyzers.query]]
name = "2xx"
from = "Status"
function = "count"
filter = { type = "between", options = { start = 200, end = 300 } }

[[analyzers.query]]
name = "3xx"
from = "Status"
function = "count"
filter = { type = "between", options = { start = 300, end = 400 } }

[[analyzers.query]]
name = "4xx"
from = "Status"
function = "count"
filter = { type = "between", options = { start = 400, end = 500 } }

[[analyzers.query]]
name = "5xx"
from = "Status"
function = "count"
filter = { type = "between", options = { start = 500, end = 600 } }

[[analyzers.query]]
name = "TotalBs"
from = "Bytes"
function = "sum"
formatOption = { alignment = "right", humanizeBytes = true }

[[analyzers.query]]
name = "MinBs"
from = "Bytes"
function = "min"
formatOption = { alignment = "right", humanizeBytes = true }

[[analyzers.query]]
name = "MeanBs"
from = "Bytes"
function = "mean"
formatOption = { alignment = "right", humanizeBytes = true }

[[analyzers.query]]
name = "MaxBs"
from = "Bytes"
function = "max"
formatOption = { alignment = "right", humanizeBytes = true }

[[analyzers.query]]
from = "Protocol"

[[analyzers.query]]
from = "Method"
formatOption = { alignment = "right" }

[[analyzers.query]]
from = "Url"


[[analyzers]]
name = "mysql"
groupingKeys = ["Query"]
sortKeys = ["Total"]
limit = 100
diffs = ["Total", "Mean"]

[analyzers.parser]
regexp = '''^([0-9]{19})\s+([0-9]+)\s+(.*)$'''

[[analyzers.parser.columns]]
name = "Timestamp"
specifier.index = 1
converters = [{ type = "parseInt64" }, { type = "unixNano" }]

[[analyzers.parser.columns]]
name = "Elapsed"
specifier.index = 2
converters = [
  { type = "parseInt64" },
  { type = "div", options = { divisor = 1e9 } },
]

[[analyzers.parser.columns]]
name = "Query"
specifier.index = 3
converters = [
  { type = "regexp", options = { replacer = "(?, ...)", pattern = '''(\(\?(, \?)+\))''' } },
]

[[analyzers.query]]
name = "Count"
from = "Elapsed"
function = "count"

[[analyzers.query]]
name = "Total"
from = "Elapsed"
function = "sum"

[[analyzers.query]]
name = "Mean"
from = "Elapsed"
function = "mean"

[[analyzers.query]]
from = "Query"
